name: "Build"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - name: "Add date to environment"
        run: echo "TODAY=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1.2.0
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: "Build test image"
        uses: docker/build-push-action@v2.8.0
        with:
          file: Dockerfile
          push: false
          platforms: linux/amd64
          tags: test-image:latest
      - name: "Run tests"
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          options: "--user root -v ${{ github.workspace }}/demo-project:/workspace:rw"
          run: |
            ./test.sh
      - name: "Login to dockerhub"
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Push images"
        run: |
          docker tag test-image:latest nbaars/owasp-dependency-check-as-one:${{ env.TODAY }}
          docker tag test-image:latest nbaars/owasp-dependency-check-as-one:latest
          docker push nbaars/owasp-dependency-check-as-one:${{ env.TODAY }}
          docker push nbaars/owasp-dependency-check-as-one:latest
      - name: "Image digest"
        run: echo ${{ steps.docker_build.outputs.digest }}