name: "Build"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
  push:
    branches:
      - main
#  schedule:
#    - cron:  '0 0 * * *'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: "Add date to environment"
        run: echo "TODAY=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1.1.0

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to dockerhub"
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push"
        uses: docker/build-push-action@v2.4.0
        with:
          file: Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            nbaars/owasp-dependency-check-as-one:${{ env.TODAY }}
            nbaars/owasp-dependency-check-as-one:latest
      - name: "Image digest"
        run: echo ${{ steps.docker_build.outputs.digest }}